
modLoader="javafml"
loaderVersion="[40,)"
license="All rights reserved"
[[mods]]
modId="phantomeq"
version="${1.18.2-0.1-ALPHA}"
displayName="PhantomEQ"
logoFile="examplemod.png"
credits=""
authors="PhantomsKeep"
description='''
A mod created for equestrian gamers seeking to improve the overall quality of the horses in Minecraft.
'''
[[dependencies.phantomeq]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.phantomeq]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
